### ISSUE TITLE
Regex for "^" and "$" are not working

### ISSUE THREAD

**Issue by jjquizon** [atom/find-and-replace#497]
I believe  my Atom editor updated itself from sometime between yesterday morning and afternoon. After the update, I can't use ^ and $ for the regex: 

![image](https://cloud.githubusercontent.com/assets/5592520/9279871/39494f40-426f-11e5-812e-b21eb66dad75.png)

I usually use this to format text (i.e. add open and close brackets at the beginning and end of line).

thomasjo in the slack channel said I should post an issue here :)

**Comment by lee-dohm** [comment]
I tried several workarounds last night:

1. Find `^(.)` and replace with `foo$1` doesn't work for blank lines
2. Find `^(.*)` and replace with `foo$1` doesn't work for blank lines
3. Same for `^(.*)$`
4. Find `\n` and replace with `\nfoo` works for all lines except the first and it creates a new line at the end of the file

Item 4 is probably the closest for now.

**Comment by signe** [comment]
I ran into this today, too.  Very frustrating.

I also ended up using the `^(.)` trick, but I wasn't working with any blank lines, just needed to prefix a bunch of data.

**Comment by xMTinkerer** [comment]
Yea, same here... I'm evaluating so I still had notepad++ available. I copied my data into there and did the replace, then copied back to Atom.

**Comment by maltebreuer** [comment]
Workaround for now would be to install the last working version, I tried it with 0.175.0. Try downgrading find-and-replace:

    apm install find-and-replace@0.175.0

I think it's down to the change in grammar, but I haven't tried anything else so far: https://github.com/atom/find-and-replace/commit/786554107ea790bd8c13b9fb6a458d570408308e#diff-a2e0f927f88fff93e2ce21d385065120

**Comment by lee-dohm** [comment]
Manually installing different versions of pre-installed packages is not recommended. There be dragons. If you want to downgrade, you should downgrade to a previous version of Atom itself.

**Comment by maltebreuer** [comment]
Sure enough they warn you a lot before installing core packages manually. Atom 1.0.3 has find-and-replace@0.175.0.

**Comment by nmat** [comment]
This is really a deal breaker for me, home and at work. I use end of line and beginning of line each and everyday for everything. Is it possible to have this prioritized for fix? :/

**Comment by think49** [comment]
I am also very troubled .
But it seems to have already passed two months , I think the prospect of this matter of the modification is not passed ?

**Comment by jonnynezbo** [comment]
I ran into this problem again today. Does any body know what the new 'beginning of line' and 'end of line' regex symbols are?

**Comment by nmat** [comment]
the normal ^ and $ searches does not really work at the moment. Not sure why. using .$ you get the result of last char but using simply $ does not work. Same as ^ for beginning of line.

Really sad it does not work.

**Comment by think49** [comment]
There is a way to consume only one character as an interim measure.

Search: "^([\s\S])"
Replace: "\1"

It works as expected of you by consuming one character [\s\S].
Is impossible "match that does not consume the character" in the current Atom.
I am anxious that this problem is resolved in Azure.

**Comment by nmat** [comment]
Not sure how used this is by others. However I always use it to setup queries and so on especially when the doc is over 100 lines.

Does anyone know what breaks with the end and beginning of line?

**Comment by MadanBhandari** [comment]
Still I can't search for `#` with any content like color code `#ddd`

**Comment by jonathanPoitz** [comment]
+1 truly frustrating!

**Comment by flakrat** [comment]
Wow, a year and a half and this is still an issue. With Sublime Text I routinely do search and replace on `^` and `$`, mostly to format text for markdown.

I recently decided to try the Atom editor. I really like the editor but just ran into this issue and very surprised at this behavior.

As mentioned above, this can be worked around, but it's strange that it's necessary:
Ex:
`Find: $` no matches, should match EOL
vs
`Fine: (.)$` matches last char + EOL

The latter requires an appropriate replace so that the final char gets put back in place, replace last char plus a space and pipe for table formatting `$1 |`

**Comment by 50Wliu** [comment]
@flakrat Please open a new issue.

**Comment by flakrat** [comment]
@50Wliu Thanks for the feedback. I was going to do just that however it appears that this now works as of version 1.15.0

Hooray!

**Comment by mubeeniqbal** [comment]
I think it's still not fixed in version 1.15.0. I had to replace the regex `^Game\.` with `Match.` and I can't. Because atom tries to replace the very string `^Game\.` instead of the string that is represented by the regex i.e. `Game.`.

**Comment by jibiel** [comment]
One thing I've noticed: _Replace All_ with `^(...)` regex and `$1` replacement works only for the files opened in the tabs.

**Comment by matthew-nm** [comment]
@jibiel <- I verify his comment. Open all the matching files and then the replace functionality will w/ regex.

thanks j!

**Comment by 50Wliu** [comment]
I have fixed this and it's currently scheduled for release in Atom 1.21.0.

**Comment by matthew-nm** [comment]
Fantastic! Thank you for looking into it.

**Comment by mrSalema** [comment]
Such a pity that this issue isn't fixed yet,

**Comment by akprajapati** [comment]
I Still face the issue. And yes even if it works some times. we have to keep selecting the regex option for each time we find and replace.

**Comment by 50Wliu** [comment]
@akprajapati This bug has already been fixed.  If you are still experiencing an issue, please open a new issue so that we can triage it.  Thanks!

**Comment by hippikon** [comment]
Hello, I am using 1.37.0 version and ^ and $ find replace does not work for this

**Comment by Arcanemagus** [comment]
As has been previously stated this _specific_ bug was fixed back in Atom v1.21.0. If you are experiencing the same symptoms please open a _new_ issue, making sure to fill out the template so we have the required information to diagnose it.

Thanks!
